SCOR = {
    "Processus": {
        "Planifier": {
            ("sP1", "Planification de la chaîne d'approvisionnement"): {
                ("sP1.1", "Identifier, Prioriser et Agréger les Besoins de la Chaîne d'Approvisionnement"),
                ("sP1.2", "Identifier, Prioriser et Agréger les Ressources de la Chaîne d'Approvisionnement"),
                ("sP1.3", "Équilibrer les Ressources de la Chaîne d'Approvisionnement avec les Exigences de la Chaîne"),
                ("sP1.4", "Élaborer et Communiquer les Plans de la Chaîne d'Approvisionnement")
            },
            ("sP2", "Planification de l'approvisionnement"): {
                ("sP2.1", "Identifier, Prioriser et Regrouper les Exigences des Produits"),
                ("sP2.2", "Identifier, Évaluer et Regrouper les Ressources des Produits"),
                ("sP2.3", "Équilibrer les Ressources Produit avec les Exigences Produit"),
                ("sP2.4", "Établir des Plans d'Approvisionnement")
            },
            ("sP3", "Plan de fabrication"): {
                ("sP3.1", "Identifier, Prioriser et Agréger les Exigences de Production"),
                ("sP3.2", "Identifier, Évaluer et Agréger les Ressources de Production"),
                ("sP3.3", "Équilibrer les Ressources de Production avec les Exigences de Production"),
                ("sP3.4", "Établir des Plans de Production")
            },
            ("sP4", "Planifier la livraison"): {
                ("sP4.1", "Identifier, Prioriser et Agréger les Exigences de Livraison"),
                ("sP4.2", "Identifier, Évaluer et Agréger les Ressources de Livraison"),
                ("sP4.3", "Équilibrer les Ressources et Capacités de Livraison avec les Exigences de Livraison"),
                ("sP4.4", "Établir des Plans de Livraison")
            },
            ("sP5", "Planifier les retours"): {
                ("sP5.1", "Évaluer et Agréger les Besoins en Retours"),
                ("sP5.2", "Identifier, Évaluer et Agréger les Ressources de Retour"),
                ("sP5.3", "Équilibrer les Ressources de Retour avec les Besoins en Retours"),
                ("sP5.4", "Établir et Communiquer les Plans de Retours")
            }
        } ,
        
        "Approvisionner": {
            ("sS1", "Approvisionner des produits stockés"): {
                ("sS1.1", "Planifier les livraisons de produits"),
                ("sS1.2", "Réceptionner les produits"),
                ("sS1.3", "Vérifier le produit"),
                ("sS1.4", "Transférer le produit"),
                ("sS1.5", "Autoriser le paiement du fournisseur")
            },
            ("sS2", "Approvisionner un produit sur commande"): {
                ("sS2.1", "Planifier les livraisons de produits"),
                ("sS2.2", "Réceptionner le produit"),
                ("sS2.3", "Vérifier le produit"),
                ("sS2.4", "Transférer le produit"),
                ("sS2.5", "Autoriser le paiement du fournisseur")
            },
            ("sS3", "Approvisionner un produit sur commande spécifique (Engineer-to-Order)"): {
                ("sS3.1", "Identifier les sources d'approvisionnement"),
                ("sS3.2", "Sélectionner le fournisseur final et négocier"),
                ("sS3.3", "Planifier les livraisons de produits"),
                ("sS3.4", "Réceptionner le produit"),
                ("sS3.5", "Vérifier le produit"),
                ("sS3.6", "Transférer le produit"),
                ("sS3.7", "Autoriser le paiement du fournisseur")
            }
        } ,
        
         "Fabriquer": {
            ("sM1", "Fabrication sur stock (Make-to-Stock)"): {
                ("sM1.1", "Planifier les activités à valeur ajoutée"),
                ("sM1.2", "Émettre le matériel / Identifier les ressources"),
                ("sM1.3", "Produire et tester"),
                ("sM1.4", "Emballer"),
                ("sM1.5", "Mettre en scène le produit / la ressource"),
                ("sM1.6", "Libérer le produit / la ressource pour la livraison"),
                ("sM1.7", "Élimination des déchets")
            },
            ("sM2", "Fabrication sur commande (Make-to-Order)"): {
                ("sM2.1", "Planifier les activités de production"),
                ("sM2.2", "Émettre le produit sourcé / en cours de production"),
                ("sM2.3", "Produire et tester"),
                ("sM2.4", "Emballer"),
                ("sM2.5", "Mettre en scène le produit fini"),
                ("sM2.6", "Libérer le produit pour la livraison"),
                ("sM2.7", "Élimination des déchets")
            },
            ("sM3", "Ingénierie sur commande (Engineer-to-Order)"): {
                ("sM3.1", "Finaliser l'ingénierie de production"),
                ("sM3.2", "Planifier les activités de production"),
                ("sM3.3", "Émettre le produit sourcé / en cours de production"),
                ("sM3.4", "Produire et tester"),
                ("sM3.5", "Emballer"),
                ("sM3.6", "Mettre en scène le produit fini"),
                ("sM3.7", "Libérer le produit fini pour la livraison"),
                ("sM3.8", "Élimination des déchets")
            }
        } ,
        
         "Livrer": {
            ("sD1", "Livrer le produit en stock"): {
                ("sD1.1", "Processus de demande et devis"),
                ("sD1.2", "Recevoir, saisir et valider la commande"),
                ("sD1.3", "Réserver l'inventaire et déterminer la date de livraison"),
                ("sD1.4", "Consolider les commandes"),
                ("sD1.5", "Construire des charges"),
                ("sD1.6", "Expéditions par route"),
                ("sD1.7", "Sélectionner les transporteurs et taux d'expédition"),
                ("sD1.8", "Recevoir le produit de la source ou fabriquer"),
                ("sD1.9", "Prélever le produit"),
                ("sD1.10", "Emballer le produit"),
                ("sD1.11", "Charger le véhicule et générer les documents d'expédition"),
                ("sD1.12", "Expédier le produit"),
                ("sD1.13", "Recevoir et vérifier les produits par le client"),
                ("sD1.14", "Installer le produit"),
                ("sD1.15", "Facture")
            },
            ("sD2", "Livrer des produits fabriqués sur commande"): {
                ("sD2.1", "Processus de demande et devis"),
                ("sD2.2", "Recevoir, configurer, saisir et valider la commande"),
                ("sD2.3", "Réserver l'inventaire et déterminer la date de livraison"),
                ("sD2.4", "Consolider les commandes"),
                ("sD2.5", "Construire des charges"),
                ("sD2.6", "Expéditions par route"),
                ("sD2.7", "Sélectionner les transporteurs et taux d'expédition"),
                ("sD2.8", "Recevoir le produit de la source ou fabriquer"),
                ("sD2.9", "Prélever le produit"),
                ("sD2.10", "Emballer le produit"),
                ("sD2.11", "Charger le véhicule et générer les documents d'expédition"),
                ("sD2.12", "Expédier le produit"),
                ("sD2.13", "Recevoir et vérifier les produits par le client"),
                ("sD2.14", "Installer le produit"),
                ("sD2.15", "Facture")
            },
            ("sD3", "Livrer un produit sur mesure"): {
                ("sD3.1", "Obtenir et répondre à RFP/RFQ"),
                ("sD3.2", "Négocier et recevoir le contrat"),
                ("sD3.3", "Saisir la commande, engager les ressources et lancer le programme"),
                ("sD3.4", "Programmer l'installation"),
                ("sD3.5", "Construire des charges"),
                ("sD3.6", "Expéditions par route"),
                ("sD3.7", "Sélectionner les transporteurs et taux d'expédition"),
                ("sD3.8", "Recevoir le produit de la source ou fabriquer"),
                ("sD3.9", "Prélever le produit"),
                ("sD3.10", "Emballer le produit"),
                ("sD3.11", "Charger le véhicule et générer les documents d'expédition"),
                ("sD3.12", "Expédier le produit"),
                ("sD3.13", "Recevoir et vérifier les produits par le client"),
                ("sD3.14", "Installer le produit"),
                ("sD3.15", "Facture")
            },
            ("sD4", "Livrer les produits de vente en détail"): {
                ("sD4.1", "Générer un calendrier de stockage"),
                ("sD4.2", "Recevoir le produit en magasin"),
                ("sD4.3", "Prélever le produit dans l'arrière-boutique"),
                ("sD4.4", "Étagère de stockage"),
                ("sD4.5", "Remplir le panier"),
                ("sD4.6", "Caisse"),
                ("sD4.7", "Livrer et/ou installer")
            }
        } ,
        
        "Retour": {
            ("sSR1", "Sourcez le produit défectueux retourné"): {
                ("sSR1.1", "Identifier l'état du produit défectueux"),
                ("sSR1.2", "Disposition produit défectueux"),
                ("sSR1.3", "Demander une autorisation de retour de produit défectueux"),
                ("sSR1.4", "Planifier l'expédition des produits défectueux"),
                ("sSR1.5", "Retourner le produit défectueux")
            },
            ("sDR1", "Livrer le produit défectueux retourné"): {
                ("sDR1.1", "Autoriser le retour effectif du produit"),
                ("sDR1.2", "Programmer une réception pour un retour défectueux"),
                ("sDR1.3", "Recevoir un produit défectueux (vérification incluse)"),
                ("sDR1.4", "Transférer le produit défectueux")
            },
            ("sSR2", "Sourcez les produits MRO retournés"): {
                ("sSR2.1", "Identifier l'état des produits MRO"),
                ("sSR2.2", "Disposition des produits MRO"),
                ("sSR2.3", "Demander une autorisation de retour de produit MRO"),
                ("sSR2.4", "Planifier l'expédition du produit MRO"),
                ("sSR2.5", "Retourner le produit MRO")
            },
            ("sDR2", "Livrer les produits MRO retournés"): {
                ("sDR2.1", "Autoriser le retour du produit MRO"),
                ("sDR2.2", "Planifier la réception du retour MRO"),
                ("sDR2.3", "Recevoir les produits MRO"),
                ("sDR2.4", "Transférer le produit MRO")
            },
            ("sSR3", "Retourner les produits excédentaires de la source"): {
                ("sSR3.1", "Identifier l'état des produits excédentaires"),
                ("sSR3.2", "Élimination des produits excédentaires"),
                ("sSR3.3", "Demander l'autorisation de retour des produits excédentaires"),
                ("sSR3.4", "Planifier l'expédition des produits excédentaires"),
                ("sSR3.5", "Retourner les produits excédentaires")
            },
            ("sDR3", "Livrer le produit excédentaire retourné"): {
                ("sDR3.1", "Autoriser le retour du produit excédentaire"),
                ("sDR3.2", "Planifier la réception du retour du produit excédentaire"),
                ("sDR3.3", "Recevoir le produit excédentaire"),
                ("sDR3.4", "Transférer le produit excédentaire")
            }
        } ,
        
         "Autoriser / Activer": {
            ("sE1","Gérer les règles métier de la chaîne d'approvisionnement")  : {
                    ("sE1.1", "Collecter les exigences des règles métier"),
                    ("sE1.2", "Interpréter les exigences des règles métier"),
                    ("sE1.3", "Documenter la règle métier"),
                    ("sE1.4", "Communiquer la règle métier"),
                    ("sE1.5", "Publier/diffuser la règle métier"),
                    ("sE1.6", "Retirer la règle métier"),
                },
            ("sE2", "Gérer la performance de la chaîne d'approvisionnement") : { 
                ("sE2.1", "Initier le reporting"), ("sE2.2", "Analyser les rapports"), 
                ("sE2.3", "Trouver les causes profondes"), 
                ("sE2.4", "Prioriser les causes profondes"), 
                ("sE2.5", "Élaborer des actions correctives"), 
                ("sE2.6", "Approuver et lancer"), 
                }, 
            ("sE3", "Gérer les données et les informations") : { 
                ("sE3.1", "Recevoir une demande de maintenance"), 
                ("sE3.2", "Déterminer/définir la portée des travaux"),
                ("sE3.3", "Maintenir le contenu/code"), 
                ("sE3.4", "Maintenir l'accès"), 
                ("sE3.5", "Publier des informations"), 
                ("sE3.6", "Vérifier les informations"), 
                },
            ("sE4", "Gérer les ressources humaines de la chaîne d'approvisionnement") : { 
                ("sE4.1", "Identifier les compétences/ressources requises"), 
                ("sE4.2", "Identifier les compétences/ressources disponibles"), 
                ("sE4.3", "Associer les compétences/ressources"), 
                ("sE4.4", "Déterminer l'embauche/le redéploiement"),
                ("sE4.5", "Déterminer la formation/l'éducation"), 
                ("sE4.6", "Approuver, prioriser et lancer"), 
            }, 
            ("sE5", "Gérer les actifs de la chaîne d'approvisionnement") : { 
                ("sE5.1", "Planifier les activités de gestion des actifs"), 
                ("sE5.2", "Mettre l'actif hors ligne"), 
                ("sE5.3", "Inspecter et dépanner"), 
                ("sE5.4", "Installer et configurer"), 
                ("sE5.5", "Nettoyer, entretenir et réparer"),
                ("sE5.6", "Mettre hors service et éliminer"), 
                ("sE5.7", "Inspecter l'entretien"), 
                ("sE5.8", "Rétablir l'actif")
                }, 
            ("sE6", "Gérer les contrats/accords de la chaîne d'approvisionnement") : { 
                ("sE6.1", "Recevoir les mises à jour du contrat/accord contractuel"), 
                ("sE6.2", "Saisir et distribuer l'accord contractuel"), 
                ("sE6.3", "Activer/archiver l'accord contractuel"), 
                ("sE6.4", "Examiner l'accord de performance contractuelle"), 
                ("sE6.5", "Identifier les problèmes/opportunités de performance"), 
                ("sE6.6", "Identifier les résolutions/améliorations"), 
                ("sE6.7", "Sélectionner, hiérarchiser et distribuer les résolutions"), 
                ("sE6.8", "Gérer la technologie de la chaîne d'approvisionnement"), 
                }, 
            ("sE7", "Gérer le réseau de la chaîne d'approvisionnement") : { 
                ("sE7.1", "Sélectionner la portée et l'organisation"), 
                ("sE7.2", "Rassembler les données et les commentaires"), 
                ("sE7.3", "Élaborer des scénarios"), 
                ("sE7.4", "Modéliser/simuler des scénarios"), 
                ("sE7.5", "Évaluer l'impact"), 
                ("sE7.6", "Sélectionner et approuver"), 
                ("sE7.7", "Élaborer un programme de changement"), 
                ("sE7.8", "Lancer un programme de changement"), 
                }, 
            ("sE8", "Gérer la conformité réglementaire et volontaire") : { 
                ("sE8.1", "Surveiller les entités réglementaires"), 
                ("sE8.2", "Évaluer les publications réglementaires"), 
                ("sE8.3", "Identifier les lacunes réglementaires"), 
                ("sE8.4", "Définir la remédiation"), 
                ("sE8.5", "Vérifier/Obtenir une licence"), 
                ("sE8.6", "Publier la remédiation"), 
                }, 
            ("sE9", "Gérer les risques de la chaîne d'approvisionnement") : { 
                ("sE9.1", "Établir le contexte"), 
                ("sE9.2", "Identifier les événements à risque"), 
                ("sE9.3", "Quantifier les risques"), 
                ("sE9.4", "Évaluer les risques"), 
                ("sE9.5", "Développer une stratégie de gestion des risques"), 
                ("sE9.6", "Surveiller"), 
                }, 
            ("sE10", "Gérer les achats de la chaîne d'approvisionnement") : { 
                ("sE10.1", "Élaborer une stratégie et un plan"), 
                ("sE10.2", "Pré-approvisionnement/Test de marché"), 
                ("sE10.3", "Élaborer la documentation"), 
                ("sE10.4", "Sélection des fournisseurs"), 
                ("sE10.5", "Émettre l'ITT/RFQ"), 
                ("sE10.6", "Évaluation et validation des offres"), 
                ("sE10.7", "Attribution et mise en œuvre du contrat"), 
                }, 
            ("sE11", "Gérer la technologie de la chaîne d'approvisionnement") : { 
                ("sE11.1", "Définir les exigences technologiques"), 
                ("sE11.2", "Identifier les solutions alternatives"), 
                ("sE11.3", "Définir la feuille de route technologique"), 
                ("sE11.4", "Sélectionner la solution technologique"), 
                ("sE11.5", "Déployer la solution technologique"), 
                ("sE11.6", "Maintenir et améliorer la solution"), 
                ("sE11.7", "Retirer la solution technologique")
                }
        }
    },
    
    #####################################################################################################
    
     "Performance": {
         "Fiabilité" : {
            ("RL1.1", "Exécution parfaite des commandes") : {},
            ("RL2.1", "% de Commandes Livrées En totalité") : {},
            ("RL2.2", "Performance de livraison par rapport à la date d'engagement du client") : {},
            ("RL2.3", "Exactitude de la documentation") : {},
            ("RL2.4", "État parfait") : {},
            ("RL3.X", "Diagnostics de fiabilité"): {
                ("RL3.1", "Nombre de plaintes concernant l'absence de documentation environnementale"),
                ("RL3.2", "Nombre de Tenue de Registres NOVs Connexes"),
                ("RL3.4", "% de documentation correcte du matériel"),
                ("RL3.5", "% Retours expédiés sans erreur"),
                ("RL3.6", "% Produits MRO Identifiés Remis en Service"),
                ("RL3.7", "% Précision de l'emplacement des articles"),
                ("RL3.10", "% des retours de produits excédentaires livrés complets au centre de retour désigné"),
                ("RL3.11", "% de factures sans erreur"),
                ("RL3.12", "% d'installations sans défaut"),
                ("RL3.13", "% des retours MRO livrés au bon prestataire de services Emplacement"),
                ("RL3.14", "% de produits répondant aux exigences de performance environnementale spécifiées"),
                ("RL3.15", "% de produits avec un étiquetage environnemental approprié (si nécessaire)"),
                ("RL3.16", "% de fournisseurs respectant les critères / indicateurs environnementaux"),
                ("RL3.17", "% de fournisseurs avec un SGE ou une certification ISO 14001"),
                ("RL3.18", "% Commandes / Lignes Traitées Complètes"),
                ("RL3.19", "% Commandes / Lignes Reçues Sans Défaut"),
                ("RL3.20", "% Commandes / Lignes Reçues à Temps selon les Exigences de Demande"),
                ("RL3.21", "% Commandes / Lignes Reçues avec le Contenu Correct"),
                ("RL3.22", "% Commandes / Lignes Reçues avec un Emballage Correct"),
                ("RL3.23", "% Commandes / Lignes Reçues avec les Documents d'Expédition Corrects"),
                ("RL3.24", "% Commandes / Lignes Reçues Sans Dommages"),
                ("RL3.25", "% Produit transféré à temps selon les exigences de la demande"),
                ("RL3.26", "% Produit transféré sans Erreurs de transaction"),
                ("RL3.27", "% des horaires modifiés dans le délai de livraison du fournisseur"),
                ("RL3.28", "% des horaires d'expédition qui respectent la date de retour requise par le client"),
                ("RL3.31", "Documentation de conformité Précision"),
                ("RL3.32", "Date d'engagement du client Temps de réalisation"),
                ("RL3.33", "Précision des articles livrés"),
                ("RL3.34", "Précision de l'emplacement de livraison"),
                ("RL3.35", "Précision de la quantité de livraison"),
                ("RL3.36", "Taux de remplissage"),
                ("RL3.37", "Précision des prévisions"),
                ("RL3.39", "Nombre d'occurrences de centre de retour désigné incorrect"),
                ("RL3.40", "Nombre d'occurrences où un excès de stock est retourné et suivi"),
                ("RL3.41", "Commandes livrées sans dommages Conformité"),
                ("RL3.42", "Commandes livrées sans défaut Conformité"),
                ("RL3.43", "Autres Documents Requis Exactitude de la Documentation"),
                ("RL3.45", "Documentation de paiement Précision"),
                ("RL3.47", "Expéditions de retours expédiées à temps"),
                ("RL3.49", "Réalisation du calendrier"),
                ("RL3.50", "Exactitude de la documentation d'expédition"),
                ("RL3.55", "Garantie et Retours"),
                ("RL3.56", "Coûts de garantie"),
                ("RL3.57", "Erreurs de traitement des déchets"),
                ("RL3.58", "Rendement"),
                ("RL3.59", "Variabilité du rendement")     
         }
          
         
       },
         
        "Réactivité": {
            ("RS.3.17", "Délai de cycle de paiement") : {},
            ("RS.3.18", "Délai de cycle de consolidation des commandes") : {},
            ("RS.3.19", "Délai de cycle actuel des retours de commandes clients") : {},
            ("RS.3.20", "Délai de cycle actuel des commandes logistiques") : {},
            ("RS.3.21", "Délai de cycle actuel des commandes de fabrication") : {},
            ("RS.3.22", "Délai de cycle actuel des retours de commandes fournisseurs") : {},
            ("RS.3.24", "Délai de cycle de livraison et/ou d'installation") : {},
            ("RS.3.25", "Délai de cycle de saisie de la commande, d'engagement des ressources et de lancement du programme") : {},
            ("RS.3.26", "Délai de cycle d'établissement et de communication des plans de retour") : {},
            ("RS.3.27", "Délai de cycle d'établissement des plans de livraison") : {},
            ("RS.3.28", "Délai de cycle d'établissement des plans de production") : {},
            ("RS.3.29", "Délai de cycle d'établissement des plans d'approvisionnement") : {},
            ("RS.3.30", "Délai de cycle d'établissement des plans de chaîne d'approvisionnement") : {},
            ("RS.3.32", "Délai de cycle de remplissage du panier") : {},
            ("RS.3.33", "Délai de cycle de finalisation de l'ingénierie de production") : {},
            ("RS.3.34", "Délai de cycle de génération du plan de stock") : {},
            ("RS.3.35", "Délai de cycle pour identifier les sources d'approvisionnement") : {},
            ("RS.3.36", "Délai de cycle pour identifier, évaluer et agréger les ressources de production") : {},
            ("RS.3.37", "Délai de cycle pour identifier, évaluer et agréger les ressources de livraison") : {},
            ("RS.3.38", "Délai de cycle pour identifier, évaluer et agréger les ressources produit") : {},
            ("RS.3.39", "Délai de cycle pour identifier, évaluer et agréger les ressources de la chaîne d'approvisionnement") : {},
            ("RS.3.40", "Délai de cycle pour identifier, prioriser et agréger les exigences de livraison") : {},
            ("RS.3.41", "Délai de cycle pour identifier, prioriser et agréger les exigences de commande de produits") : {},
            ("RS.3.42", "Délai de cycle pour identifier, prioriser et agréger les exigences de production") : {},
            ("RS.3.43", "Délai de cycle pour identifier, prioriser et agréger les exigences de retour") : {},
            ("RS.3.44", "Délai de cycle pour identifier, prioriser et agréger les exigences de la chaîne d'approvisionnement") : {},
            ("RS.3.45", "Délai de cycle pour l'installation du produit") : {},
            ("RS.3.46", "En stock") : {},
            ("RS.3.47", "Délai de cycle de facturation") : {},
            ("RS.3.48", "Délai de cycle de distribution des matériaux") : {},
            ("RS.3.49", "Délai de cycle de distribution des produits sourcés / en cours de fabrication") : {},
            ("RS.3.50", "Délai de cycle pour charger le produit et générer la documentation d'expédition") : {},
            ("RS.3.51", "Délai de cycle pour maintenir les données sources") : {},
            ("RS.3.52", "Délai de cycle pour gérer les règles métier pour le processus de planification") : {},
            ("RS.3.53", "Délai de cycle pour gérer les règles métier pour les processus de retour") : {},
            ("RS.3.54", "Délai de cycle pour gérer les actifs immobilisés") : {},
            ("RS.3.55", "Délai de cycle pour gérer les règles métier pour la livraison") : {},
            ("RS.3.56", "Délai de cycle pour gérer la livraison des actifs immobilisés") : {},
            ("RS.3.57", "Délai de cycle pour gérer les informations de commande de livraison") : {},
            ("RS.3.58", "Délai de cycle pour gérer les exigences d'importation / exportation") : {},
            ("RS.3.59", "Délai de cycle pour gérer l'information des commandes de livraison") : {},
            ("RS.3.61", "Délai de cycle pour gérer les exigences d'importation/exportation") : {},
            ("RS.3.64", "Délai de cycle pour gérer les actifs immobilisés de la chaîne d'approvisionnement intégrée") : {},
            ("RS.3.65", "Délai de cycle pour gérer l'inventaire de la chaîne d'approvisionnement intégrée") : {},
            ("RS.3.66", "Délai de cycle pour gérer le transport de la chaîne d'approvisionnement intégrée") : {},
            ("RS.3.67", "Délai de cycle pour gérer les équipements et installations de fabrication") : {},
            ("RS.3.68", "Délai de cycle pour gérer les informations de fabrication") : {},
            ("RS.3.70", "Délai de cycle pour gérer la performance des processus de retour") : {},
            ("RS.3.71", "Délai de cycle pour gérer la performance de la chaîne d'approvisionnement") : {},
            ("RS.3.72", "Délai de cycle pour gérer la collecte des données de planification") : {},
            ("RS.3.74", "Délai de cycle pour gérer le réseau de production") : {},
            ("RS.3.77", "Délai de cycle pour gérer la performance de la production") : {},
            ("RS.3.78", "Délai de cycle pour gérer les règles de production") : {},
            ("RS.3.79", "Délai de cycle pour gérer les actifs immobilisés de retour") : {},
            ("RS.3.80", "Délai de cycle pour gérer la collecte des données de retour") : {},
            ("RS.3.81", "Délai de cycle pour gérer la configuration du réseau de retour") : {},
            ("RS.3.83", "Délai de cycle pour gérer le transport des retours") : {},
            ("RS.3.85", "Délai de cycle pour gérer le transport des retours") : {},
            ("RS.3.86", "Délai de cycle pour gérer les règles métier de sourcing") : {},
            ("RS.3.87", "Délai de cycle pour gérer les accords avec les fournisseurs") : {},
            ("RS.3.88", "Délai de cycle pour gérer les commandes du réseau de fournisseurs") : {},
            ("RS.3.89", "Délai de cycle pour gérer le transport (travail en cours)") : {},
            ("RS.3.90", "Délai de cycle pour gérer le transport") : {},
            ("RS.3.92", "Délai de cycle pour négocier et recevoir un contrat") : {},
            ("RS.3.93", "Délai de cycle pour obtenir et répondre à une demande de devis (RFQ)/demande de proposition (RFP)") : {},
            ("RS.3.94", "Temps de séjour pour l'exécution de commande") : {},
            ("RS.3.95", "Délai de cycle pour emballer le produit") : {},
            ("RS.3.96", "Délai de cycle pour préparer le produit") : {},
            ("RS.3.97", "Délai de cycle pour prendre le produit du stock arrière") : {},
            ("RS.3.98", "Délai de cycle pour la planification") : {},
            ("RS.3.99", "Délai de cycle pour planifier l'approvisionnement") : {},
            ("RS.3.100", "Délai de cycle pour traiter les demandes et devis") : {},
            ("RS.3.101", "Délai de cycle pour produire et tester") : {},
            ("RS.3.102", "Délai de cycle pour recevoir et vérifier le produit par le client") : {},
            ("RS.3.103", "Délai de cycle pour recevoir et vérifier le produit") : {},
            ("RS.3.104", "Délai de cycle pour recevoir un produit défectueux") : {},
            ("RS.3.105", "Délai de cycle pour recevoir un produit excédentaire") : {},
            ("RS.3.106", "Délai de cycle pour recevoir un produit MRO") : {},
            ("RS.3.107", "Délai de cycle pour recevoir le produit") : {},
            ("RS.3.108", "Délai de cycle pour recevoir le produit de la fabrication / de l'approvisionnement") : {},
            ("RS.3.109", "Délai de cycle pour recevoir le produit en magasin") : {},
            ("RS.3.110", "Délai de cycle pour recevoir le produit de la source ou de la fabrication") : {},
            ("RS.3.111", "Délai de cycle pour recevoir, configurer, entrer et valider") : {},
            ("RS.3.112", "Délai de cycle pour recevoir, entrer et valider la commande") : {},
            ("RS.3.113", "Délai de cycle pour la réception du produit") : {},
            ("RS.3.114", "Délai de cycle pour libérer le produit fini pour livraison") : {},
            ("RS.3.115", "Délai de cycle pour le traitement des retours") : {},
            ("RS.3.116", "Délai de cycle pour le retour des produits défectueux") : {},
            ("RS.3.117", "Délai de cycle pour le retour des produits excédentaires") : {},
            ("RS.3.118", "Délai de cycle pour le retour des produits MRO") : {},
            ("RS.3.119", "Délai de cycle pour la disposition des produits") : {},
            ("RS.3.120", "Délai de cycle pour le réapprovisionnement") : {},
            ("RS.3.121", "Délai de cycle pour la mise au rebut des produits défectueux") : {},
            ("RS.3.122", "Délai de cycle pour le tri des retours") : {},
            ("RS.3.123", "Délai de cycle pour les contrôles qualité sur les retours") : {},
            ("RS.3.124", "Délai de cycle pour le réapprovisionnement des stocks") : {},
            ("RS.3.125", "Délai de cycle pour le recyclage des matériaux") : {},
            ("RS.3.126", "Délai de cycle pour la gestion des crédits de retour") : {},
            ("RS.3.127", "Délai de cycle pour la planification du recyclage") : {},
            ("RS.3.128", "Délai de cycle pour l'entreposage des retours") : {},
            ("RS.3.129", "Délai de cycle pour la redistribution des produits retournés") : {},
            ("RS.3.130", "Délai de cycle pour la transformation des matériaux recyclés") : {},
            ("RS.3.131", "Délai de cycle pour le traitement des produits obsolètes") : {},
            ("RS.3.132", "Délai de cycle pour la récupération des composants des produits retournés") : {},
            ("RS.3.133", "Délai de cycle pour la revente des produits retournés") : {},
            ("RS.3.134", "Délai de cycle pour le retour des actifs") : {},
            ("RS.3.135", "Délai de cycle pour l'inspection des actifs retournés") : {},
            ("RS.3.136", "Délai de cycle pour la remise à neuf des actifs") : {},
            ("RS.3.137", "Délai de cycle pour la mise à disposition des actifs retournés") : {},
            ("RS.3.138", "Délai de cycle pour la gestion des inventaires excédentaires") : {},
            ("RS.3.139", "Délai de cycle pour la réutilisation des actifs") : {},
            ("RS.3.140", "Délai de cycle pour la gestion des pièces détachées") : {},
            ("RS.3.141", "Délai de cycle pour la gestion des garanties") : {},
            ("RS.3.142", "Délai de cycle pour la gestion des litiges sur les retours") : {}
       },
 
         "Agilité": {
            ("AG.1.1", "Adaptabilité de la chaîne d'approvisionnement à la hausse") : {},
            ("AG.2.2", "Adaptabilité à la hausse (Fabrication)") : {},
            ("AG.2.3", "Adaptabilité à la hausse (Livraison)") : {},
            ("AG.2.4", "Adaptabilité à la hausse des retours") : {},
            ("AG.2.5", "Adaptabilité à la hausse des retours (Livraison)") : {},
            ("AG.1.2", "Adaptabilité de la chaîne d'approvisionnement à la baisse") : {},
            ("AG.2.6", "Adaptabilité à la baisse (Approvisionnement)") : {},
            ("AG.2.7", "Adaptabilité à la baisse (Fabrication)") : {},
            ("AG.2.8", "Adaptabilité à la baisse (Livraison)") : {},
            ("AG.1.4", "Valeur totale en risque (VAR)") : {},
            ("AG.2.9", "Évaluation du risque du fournisseur, du client ou du produit") : {},
            ("AG.2.10", "Valeur en risque pour la planification (Plan Value at Risk)") : {},
            ("AG.2.11", "Valeur en risque pour l'approvisionnement (Source Value at Risk)") : {},
            ("AG.2.12", "Valeur en risque pour la fabrication (Make Value at Risk)") : {},
            ("AG.2.13", "Valeur en risque pour la livraison (Deliver Value at Risk)") : {},
            ("AG.2.14", "Valeur en risque pour les retours (Return Value at Risk)") : {},
            ("AG.2.15", "Temps de Récupération (TTR)") : {}
         },
         
          "Coût": {
            ("CO.1.1", "Coût Total de Gestion de la Chaîne d'Approvisionnement (CTGCA)") : {},
            ("CO.2.1", "Coût de la planification"): {},
            ("CO.2.2", "Coût d'approvisionnement") : {},
            ("CO.2.3", "Coût de fabrication") : {},
            ("CO.2.4", "Coût de livraison et/ou d'installation") : {},
            ("CO.2.5", "Coût de retour") : {},
            ("CO.2.6", "Coûts d'atténuation des risques") : {},
            ("CO.1.2", "Coût des marchandises vendues (COGS)") : {},
            ("CO.2.7", "Coût de la main-d'œuvre directe") : {},
            ("CO.2.8", "Coût des matériaux directs") : {},
            ("CO.2.9", "Coût indirect lié à la production") : {},
            ("CO.3.X", "Diagnostic du coût") :  {
                ("CO.3.1", "Coût de planification de la chaîne d'approvisionnement") ,
                ("CO.3.2", "Coût de planification de la source"),
                ("CO.3.3", "Coût de Planification de Fabrication"),
                ("CO.3.4", "Coût de Planification de Livraison"),
                ("CO.3.5", "Coût de Planification du Retour"),
                ("CO.3.6", "Coût pour autoriser le paiement du fournisseur"),
                ("CO.3.7", "Coût pour recevoir le produit"),
                ("CO.3.8", "Coût pour planifier les livraisons de produits"),
                ("CO.3.9", "Coût de transfert du produit"),
                ("CO.3.10", "Coût de vérification du produit"),
                ("CO.3.11", "Coût des matériaux directs"),
                ("CO.3.12", "Coût Indirect Lié à la Production"),
                ("CO.3.13", "Coût de la main-d'œuvre directe"),
                ("CO.3.14", "Coûts de gestion des commandes"),
                ("CO.3.15", "Coûts de livraison et/ou d'installation de la commande"),
                ("CO.3.16", "Coût de retour de la source"),
                ("CO.3.17", "Coût de livraison du retour"),
                ("CO.3.18", "Coûts de mitigation des risques (Plan)"),
                ("CO.3.19", "Coûts de mitigation des risques (Source)"),
                ("CO.3.20", "Coûts d'atténuation des risques (fabrication)"),
                ("CO.3.21", "Coûts d'atténuation des risques (livraison)"),
                ("CO.3.22", "Coûts d'atténuation des risques (retour)")
            },
       },
         
          "Gestion d'actifs": {
            ("AM.1.1", "Cycle de Trésorerie (Cash-to-Cash Cycle Time)") : {} ,
            ("AM.2.1", "Délai de Recouvrement des Créances Clients") : {} ,
            ("AM.2.2", "Jours de Stock Disponible") : {} ,
            ("AM.2.3", "Délai de Paiement Fournisseurs") : {} ,
            ("AM.1.2", "Retour sur les Actifs Fixes de la Chaîne d’Approvisionnement") : {} ,
            ("AM.2.4", "Revenu de la Chaîne d’Approvisionnement") : {} ,
            ("AM.2.5", "Actifs Fixes de la Chaîne d’Approvisionnement") : {} ,
            ("AM.1.3", "Retour sur le Fonds de Roulement") : {} ,
            ("AM.2.6", "Comptes Fournisseurs") : {} ,
            ("AM.2.7", "Comptes Clients") : {} ,
            ("AM.2.8", "Stock") : {} ,
            ("AM.3.X", "Diagnostics pour la Gestion des Actifs") : {} ,
        },

         
     },
    
    ###########################################################################################
    
    "Pratiques" : {
         "Pratique émergente": {
         ("BP.120", "Impression 3D / Prototypage Rapide (3D Print/Rapid Prototyping)") : {} ,
         ("BP.121", " Emballage Numérique à la Demande (Digital Packaging on Demand)") : {} ,
         ("BP.150", "Maintenir un Registre des Risques de la Chaîne d’Approvisionnement (Maintain Supply Chain Risk Register)") : {} ,
         ("BP.176", "Omni-canal (Omni-channel)") : {} ,
         ("BP.177", "Fabrication Additive (Additive Manufacturing)") : {} ,
         ("BP.178", "Blockchain") : {} ,
         ("BP.179", "MRP Piloté par la Demande (Demand Driven MRP - DDMRP)") : {} ,
         ("BP.180", "S&OP Piloté par la Demande (Demand Driven S&OP - DDS&OP)") : {} ,
         ("BP.183", "Planification Intégrée des Affaires (IBP - Integrated Business Planning)") : {} ,
         ("BP.184", "Planification de Scénarios (Scenario Planning)") : {} ,
         ("BP.188", "Synchronisation des Objets SCM - Correspondance à 3/4 Voies") : {} ,
           },
    "Meilleures pratiques": {
        ("BP.002", "Stratégies de gestion des risques") : {} ,
        ("BP.003", "Changement d'outil en moins d'une minute (SMED)") : {} ,
        ("BP.109" , "Pré positionnement des carcasses") : {} ,
        ("BP.103" , "Rationalisation des articles") : {} ,
        ("BP.016" , "Planification du réseau d'approvisionnement") : {} ,
        ("BP.024" , "Optimisation de la chaîne d'approvisionnement (SCO)") : {} ,
        ("BP.025" , "Soumission de réclamations de garantie en libre-service") : {} ,
        ("BP.026" , "Amélioration du processus S&OP") : {} ,
        ("BP.027" , "Réapprovisionnement basé sur la demande (Pull-Based Inventory Replenishment)") : {} ,
        ("BP.028", "Optimisation des Stocks") : {} ,
        ("BP.029", "Optimisation du Réseau") : {} ,
        ("BP.031", "Rationalisation des Unités de Stock (SKU) / Analyse du Coût des Ventes") : {} ,
        ("BP.034", "Étendre la Planification des Stocks avec la Collaboration (Fournisseurs Clés)") : {} ,
        ("BP.041", "Optimisation du Transport") : {} ,
        ("BP.048", "Modelage de la Demande") : {} ,
        ("BP.049", "Planification Lean") : {} ,
        ("BP.052", "Gestion de la Conception pour la Logistique (DFL)") : {} ,
        ("BP.053", "Amélioration de la Fiabilité de la Production") : {} ,
        ("BP.055", "Évaluation de la Performance des Transporteurs") : {} ,
        ("BP.062", "Précision des Données Maîtres") : {} ,
        ("BP.071", "Optimisation des Modes de Transport") : {} ,
        ("BP.074", "Alignement des Processus/Mesures") : {} ,
           },
    "Pratique standard" : {
        ("BP.001", "Gestion des Risques de la Chaîne d'Approvisionnement (SCRM)") : {} ,
        ("BP.004", "Priorisation du Réseau pour l'Identification des Risques") : {} ,
        ("BP.005", "Auto-Facturation") : {} ,
        ("BP.006", "Stocks en Consignation") : {} ,
        ("BP.007", "Suivi de l'Inventaire de Référence") : {} ,
        ("BP.008", "Suivi des Stocks Lents") : {} ,
        ("BP.009", "Kanban") : {} ,
        ("BP.010", "Min-Max Replanissement") : {} ,
        ("BP.011", "Séquencement de la ligne de production") : {} ,
        ("BP.012", "Suivi des lots") : {} ,
        ("BP.014", "Planification de la demande et prévision") : {} ,
        ("BP.015", "Planification du stock de sécurité") : {} ,
        ("BP.017", "Planification de la distribution") : {} ,
        ("BP.018", "Système de classification ABC des stocks") : {} ,
        ("BP.021", "La planification des ventes et des opérations") : {}
    },

    },

    ########################################################################################################
    "Personnes" : {
        "Compétence" : {
         ("HS.002", "Tests d'Acceptation") : {},
         ("HS.003", "Comptabilité") : {},
         ("HS.004", "Méthodolgies Publicitaires") : {},
         ("HS.005", "Conception du Processus d'Assemblage") : {},
         ("HS.006", "Gestion des actifs") : {},
         ("HS.007", "Gestion de la disponibilité") : {},
         ("HS.012", "Benchmarking") : {},
         ("HS.015", "CAO/ FAO(Conception et Fabrication assistées par ordinateur)") : {},
         ("HS.016", "Planfication/ Gestion de la Capacité") : {},
         ("HS.018", "Sélection du transporteur") : {},
         ("HS.0139", "Appel d'offres concurrentiel") : {},
         ("HS.0022", "Gestion des contrats") : {},
         ("HS.0025", "Gestion des Règles Métier/Politiques") : {},
         ("HS.0028", "Gestion des commandes clients") : {},
         ("HS.0029", "Gestion de la relation Client (CRM)") : {},
         ("HS.0032", "Communication Client/Fournisseur") : {},
         ("HS.0124", "Gestion des Données et Analyse") : {},
         ("HS.0036", "Planification des livraisons") : {},
         ("HS.0037", "Gestion de la demande") : {},
         ("HS.0094", "Approvisionnement") : {},
         ("HS.0108", "Gestion de la qualité") : {},
         ("HS.0121", "Développement de la Stratégie des Retours") : {},
         ("HS.0124", "Gestion des Risques et des Exceptions") : {},
         ("HS.0139", "Gestion des Relations Fournisseurs (SRM)") : {},
         ("HS.0144", "Sécurité de la Chaine d'Approvisionnement") : {},
         ("HS.0165", "Gestion du Changement") : {},
            
        },
        
        "Expérience" : {
         ("HE.0009", "Codage à barres/RFID") : {},
         ("HE.0010", "Finance de base") : {},
         ("HE.0108", "Stratégie de couverture des prix du carburant") : {},
         ("HE.0162", "Techniques de modélisation") : {},
         ("HE.0205", "Gestion de projet") : {},
         ("HE.0224", "Gestion des risques") : {},
         ("HE.0251", "modélisation/Analyse statistique") : {},
         ("HE.0265", "Accords sur la stratégie de service fournisseur") : {},
         ("HE.0269", "Gestion de la perfomance de la chaine d'approvisionnement/Mesures") : {},
         ("HE.0303", "Système de notation des fournisseurs") : {},
         ("HE.0304", "Gestion des entrepots/distribution") : {},
         ("HE.0305", "Gestion des stocks Min/Max") : {},
         ("HE.0306", "Procédure de gestion des déchets") : {},
         ("HE.0307", "Spider aquatique (terme logistique pour un opérateur de manutention)") : {},
         ("HE.0308", "Méthodolgie du WIP (Work In Progress - Travaux en cours)") : {}, 
         ("HE.0309", "Reportassions des travaux en cours") : {},
        },
        
        "Formation" : {
         ("HT.0001", "Principes avancés de Comptabilité") : {},
         ("HT.0002", "Techniques avancées d'Excel") : {},
         ("HT.0003", "Négociations avancées/Planification collaborative") : {},
         ("HT.0004", "Méthodologies publicitaires") : {},
         ("HT.0005", "Construction d'accords/Exigences juridiques") : {},
         ("HT.0006", "Certification APICS CPIM - Production et Gestion des stocks") : {},
         ("HT.0007", "Certification APICS CSCP - Professionel de la Chaine d'Approvisionnement") : {},
         ("HT.0017", "Modèle économique et canal de vente") : {},
         ("HT.0027", "Résolution de conflits") : {},
         ("HT.0034", "CPER (Cycle de Planification, Execution et Révision)") : {},
         ("HT.0037", "Certification APICS CTLD - logistique, transport et distribution") : {},
         ("HT.0060", "Techniques de prévision") : {},
         ("HT.0066", "Ingénierie des systèmes verts") : {},
         ("HT.0067", "Certification IBF (Institute of Business Forecasting)") : {},
         ("HT.0070", "Certification réglementaires spécifiques à l'industrie") : {},
         ("HT.0080", "Certification ISO") : {},
         ("HT.0102", "Compétences en Négociation") : {},
         ("HT.0122", "Formation S&OP (Oliver Wight, Tom Wallace ou équivalent)") : {},
         ("HT.0127", "Certification SCOR-P") : {},
         ("HT.0128", "SCOR mark") : {},
         ("HT.0133", "Six Sigma Greenbelt") : {},
         ("HT.0157", "Principes APICS de distribution et logistique") : {},
         ("HT.0158", "Principes APICS de gestion des stocks") : {},
         ("HT.0159", "Principes APICS de gestion des opérations") : {},
         ("HT.0160", "Principes APICS de gestion de la Production") : {},
         ("HT.0161", "Principes APICS de Planification des opérations") : {},


           
      }
        
    }
    
    
}